### ISSUE TITLE
Paper DeepRemaster's model file format corruption

### ISSUE THREAD

**Issue by studentzhuang** [MarkMoHR/Awesome-Image-Colorization#15]
Excuse me,I wanna try to use the model of DeepRemaster,and I download the model using the sh file through gitbash.After that,I get a model with postfix tar.I am trying to unzip the file and always  stoped by file format corruption. Could you tell me how to do with this situation?Maybe you can tell me another way to get this model if possible.Thank you very much!
![image](https://user-images.githubusercontent.com/74413071/99075665-d45c5180-25f4-11eb-8da5-be065f51a93b.png)

**Comment by MarkMoHR** [comment]
Hi @studentzhuang ,
You could open an issue in the DeepRemaster's repo
