### ISSUE TITLE
a project link for the cvpr2020 paper

### ISSUE THREAD

**Issue by SSUHan** [MarkMoHR/Awesome-Image-Colorization#19]
Thanks for your awesome work!

I recommend an official project link for the CVPR'20 paper named "Reference-Based Sketch Image Colorization
using Augmented-Self Reference and Dense Semantic Correspondence" as below:

https://ssuhan.github.io/RSC_CVPR20/

Thanks in advance!

**Comment by MarkMoHR** [comment]
Done. Thanks!
