### ISSUE TITLE
Request to add a new paper

### ISSUE THREAD

**Issue by piddnad** [MarkMoHR/Awesome-Image-Colorization#27]
We would like to introduce our automatic colorization work accepted by ICCV 2023, called DDColor.

DDColor: Towards Photo-Realistic Image Colorization via Dual Decoders

Paper: https://arxiv.org/abs/2212.11613
Code: https://github.com/piddnad/DDColor
Demo: https://www.modelscope.cn/models/damo/cv_ddcolor_image-colorization/summary

Appreciate your efforts. This list of colorization is AWESOME!

**Comment by MarkMoHR** [comment]
Done. Thanks!
